name: Events workflow from dev branch
on:
    pull_request:
      types: [opened, edited]
      branches: 
        - main #main
        - dev # dev-new or dev-this-is-new
        - feat/** # feat/new or feat/this/is/new
    workflow_dispatch:
    push:
      branches: 
        - main #main
        - dev # dev-new or dev-this-is-new
        - feat/** # feat/new or feat/this/is/new
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Deploy
        run: echo "Deploying..."